### ISSUE TITLE
`promised` function does not always return a promise

### ISSUE THREAD

**Issue by pcaisse** [arc-repos/arc-data#14]
In the [Persist Data](https://arc.codes/guides/data) tutorial, the code for `make-person.js` is as follows:

```js
module.exports = async function makePerson(email, suppliedPassword) {
  let hashedPassword = await bcrypt.hash(suppliedPassword, SALT_ROUNDS)
  let person = {email, password: hashedPassword}
  data.people.put(person)
  log(`Created person ${email}`)
  return person
}
```

This style of assuming that the data was written to the database and then returning the JS object in memory works fine when running locally, but in an actual lambda this doesn't seem to be the case -- my lambda was not actually saving new people to the database. I believe it's because the lambda terminates before the async request is made.

```js
return await data.people.put(person)  // this works!
```

Which brings us to the crux of the issue: in trying to debug this, the first thing I did was try the following:

```js
data.people.put(person, console.log)
```

This set me up for failure since the [promised](https://github.com/arc-repos/arc-data/blob/master/src/_promisify-object.js#L21) function confusingly doesn't always return a promise, so I had unwittingly shot myself in the foot. Even doing the ostensibly correct thing (adding the `await`) won't work if you pass in a callback:
 
```js
return await data.people.put(person, console.log)  // this doesn't work
```

IMHO `promised` should always return a promise.

**Comment by brianleroux** [comment]
ah sorry, our docs should be clearer. we return a promise if you do not supply a callback. in your examples above, you are supplying a callback of `console.log`. where do you think we could make this more prominent? we def want to support both promised and idiomatic node errback code.

**Comment by pcaisse** [comment]
> where do you think we could make this more prominent?

IMHO I think the API should work differently. To me, it seems very unexpected for adding an optional callback to change the type that is returned. I was expecting the callback function to be called with the result of the promise before it resolved/rejected, essentially as an easy way to hook into the result/err (hence the `console.log` so I could have insight into why writing data to the database wasn't working). Then again, I'm not a node developer so maybe my expectations are weird! :wink: 

I would prefer to have a separate function, like `putCallback`, which takes two parameters -- an object and a function -- both of which are required. That way it's very explicit and the API itself would call out the difference in terms of what you get back.

**Comment by brianleroux** [comment]
Yeah the error first callback as the last parameter is idiomatic Node. Promise is newer but more popular because web browsers have been moving that way. Most of the Node API itself is of the form `thing(param, errback)` where errback is a function of hte form `(err, result)=>`. As the Promise primitive became more popular A LOT of folks were asking for support. So this is, imo, the cleanest way to support both styles. (Updating the docs to fix that missing `await`.)
