### ISSUE TITLE
Convenience method for indexes on DynamoDB tables?

### ISSUE THREAD

**Issue by mrb** [arc-repos/arc-data#2]
The name generated for a Dynamo index with the following configuration:

```
@indexes
jams
  sentiment *String
```

produces index names like `brainjams-staging-jams-sentiment-index` etc.

Similarly to how `data.jams` knows the db, could we get something like `data.jams.index('sentiment')` which can dynamically find the right index so we don't have to know that string at all?

**Comment by brianleroux** [comment]
yes, this is a pita sorry! I have an issue to do ref docs that improve this experience. there is a hidden helper function on data called `_name` to help get the right name for a given thing in a given env. 

```javascript
let arc = require('@architect/data')

console.log(data._name('jams-sentiment-index'))
```

…should return what you want so you can compose a more complex query or whatever. 

code ref here: 

https://github.com/arc-repos/arc-data/blob/master/_init.js#L16

**Comment by mrb** [comment]
Nice thanks!
