### ISSUE TITLE
.arc file not found

### ISSUE THREAD

**Issue by wallyatkins** [arc-repos/arc-data#3]
I'm not sure if I've missed a step somewhere but I am receiving an error when running `arc-repl`

Following the guide: [Intro To DynamoDB](https://viewsource.codes/03-intro-to-ddb)

`ReferenceError: .arc file not found: /path/to/arc-workshop/node_modules/@architect/shared/.arc`
`    at Object.<anonymous> (/path/to/arc-workshop/node_modules/@architect/data/index.js:25:9)`
`    at Module._compile (module.js:652:30)`
`    at Object.Module._extensions..js (module.js:663:10)`
`    at Module.load (module.js:565:32)`
`    at tryModuleLoad (module.js:505:12)`
`    at Function.Module._load (module.js:497:3)`
`    at Module.require (module.js:596:17)`
`    at require (internal/module.js:11:18)`
`    at Object.<anonymous> (/path/to/arc-workshop/node_modules/@architect/data/repl.js:2:12)`
`    at Module._compile (module.js:652:30)`

I copied the `.arc` file to the path it was looking for and it will run `arc-repl` so I can work around it for now but I wasn't sure where the actual problem resides.

**Comment by brianleroux** [comment]
Oh no! need to update these docs; I think it might be looking for NODE_ENV=testing and ARC_LOCAL=1 env vars to be set if you're running locally. (Otherwise it looks in the architect/shared module thinking its running in a lambda instead of locally)

lmk if that was it and I'll update the docs!

**Comment by brianleroux** [comment]
hey @wallyatkins closing this issue but feel free to reopen or comment if you need further help or clarification

**Comment by mikemaccana** [comment]
Should https://arc.codes/guides/data mention `ARC_LOCAL` is needed (looking at `arc-data/index.js`? I think it is)

Is there a better way to tell we're running in sandbox, so we wouldn't have the requirement?

**Comment by ryanblock** [comment]
`ARC_LOCAL` is not a requirement for `arc-data`, please see: https://github.com/arc-repos/arc-data/issues/6#issuecomment-454423495
