### ISSUE TITLE
Can't find .arc file (arcPath is undefined)

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/arc-data#6]
@architect/data 2.0.9 on Windows 10. Going to check it out (the .arc file obviously exists and you can see `npx sandbox` using it) myself, but if you have any suggestions throw them here!

    C:\Users\mikem\OneDrive\Documents\arc-example-auth\node_modules\@architect\data\index.js:31
    throw ReferenceError('.arc file not found: ' + arcPath)
    ^

    ReferenceError: .arc file not found: undefined

**Comment by mikemaccana** [comment]
Dupe of https://github.com/arc-repos/arc-data/issues/3

But why does arc-data need `NODE_ENV=testing` and `ARC_LOCAL=1` set explicitly when it finds the `.arc` file just fine without it? It seems like there should be a shared module that finds the `.arc` file - so it's handled consistently everywhere.

**Comment by mikemaccana** [comment]
Thanks Ryan. The issue is with `arc-data` - the `architect` module is fine. I've updated `architect` to 4.5.2 anyway but the issue still exists.

**Comment by mikemaccana** [comment]
Wait I think I misinterpreted something Brian said in https://github.com/arc-repos/arc-data/issues/3 - 

**is NODE_ENV=testing and ARC_LOCAL=1 for development of `arc-data` itself?** 

I thought they were needed to fix this, but it looks like something else fixed this and NODE_ENV=testing and ARC_LOCAL=1 are **causing** this.

**Comment by ryanblock** [comment]
I've got a bit of an understanding gap right now. Can you post clear repro steps with the env vars you're using, and what you're trying to accomplish? Sounds like something's wrong but I need a bit more info to diagnose. Thanks!

**Comment by mikemaccana** [comment]
Sure, I'll send a repo with some basic steps shortly.

**Comment by mikemaccana** [comment]
## What you're trying to accomplish?

Have this line work:

`let data = require('@architect/data')`

## the env vars you're using

None right now. I hope that, like the `architect` module the `data` module works without any env vars being set. This does not seem to be correct though. `@architect\data\index.js:30:20` tries to load the `.arc` file from `arc-example\src\http\get-protected\.arc` where it doesn't exist, rather than `arc-example\.arc` where it does

**Comment by ryanblock** [comment]
Looks like you're probably using Arc version `4.4.12` or `4.4.13`, and did not generate a `src/shared` dir in your project. As I mentioned earlier in the thread, a bug introduced in `4.4.12` (which was fixed in `4.5.0`) stops copying the `.arc` file into `src/${type}/${function}/node_modules/@architect/shared/.arc` when `sandbox` is run.

If that looks right, your options to fix are to upgrade (of course), or create `src/shared` and put any file in there. Also, be sure that you have something in `@tables` in your arc file, or `arc-data` will crash. (This can be improved.)

There is another scenario here, which is that you're not using a `.arc` file at all, but are instead using `app.arc`, `arc.yaml`, or `arc.json`. Currently `arc-data` (and `arc-functions`) does not attempt to read those files, and that is indeed a bug, which I'll go file separately.

**Comment by mikemaccana** [comment]
As mentioned [above](https://github.com/arc-repos/arc-data/issues/6#issuecomment-452731832):

>  I've updated architect to 4.5.2 anyway but the issue still exists. 

`src/shared` exists

**Comment by mikemaccana** [comment]
OK in https://github.com/arc-repos/arc-data/issues/3#issuecomment-454424545 you mentioned the answer is B (`ARC_LOCAL` doesn't need to be set) 

https://github.com/arc-repos/arc-data/blob/f1c4be0d2b46f981324a301e4204091315ab4967/index.js#L12 only sets the arc4 sandbox location if `ARC_LOCAL` is set. So this is a bug and still outstanding.

**Comment by ryanblock** [comment]
To answer your question: B.

Sorry for confusion about Arc version, you did mention that. I have attempted to replicate your bug but have been unable to.

Please post node version, arc version, arc file, arc project file tree, and any relevant arc-data caller code.

All that said, looking at that code, it looks correct to me, and again, I can’t replicate it not finding an .arc file, so I need a lot more info.

We can also jump on a Zoom call today if that works for you!

**Comment by mikemaccana** [comment]
Hah I was literally writing an email (was going to try slack first but I couldn't find the channel) !  Sorry if I've been vague with the bug report, there's a conflict between the docs, and comments in various other bug reports. 

You can replicate with this repo (I'm making an arc-data example using the new lambda and middleware signatures), based on the `arc-example-login-flow`. https://github.com/mikemaccana/arc-example-login-flow

This seems like a pretty simple issue: the 'Arc 4 Sandbox' location never gets set if ARC_LOCAL isn't set - you can just read https://github.com/arc-repos/arc-data/blob/f1c4be0d2b46f981324a301e4204091315ab4967/index.js#L12 AFAICT there's nothing else to it. The PR fixes it.

**Comment by ryanblock** [comment]
Thanks, will take a look at replication as soon as I get back I my desk!

**Comment by ryanblock** [comment]
Ok, I see the issue, and see why it wasn't replicating for me. Looks like some legacy assumptions made that we didn't see internally over here based on the way we're using Arc, and hadn't noticed in anger. Posting up notes in the new PR I pulled yours into: https://github.com/arc-repos/arc-data/pull/11

**Comment by ryanblock** [comment]
This `arc-data` fix now published to NPM as `2.0.10@beta`
Similar `arc-functions` fix published to NPM as `1.11.2@beta`
Please validate!

**Comment by ryanblock** [comment]
No sweat, thanks for your patience in getting this here!

**Comment by mikemaccana** [comment]
Have been using the betas for 24 hours and it's fine now. Consider it closed! 👍

**Comment by ryanblock** [comment]
Now published to NPM@latest in `2.0.12`!
